"""Initial

Revision ID: 6e5c2eec8dd2
Revises: 
Create Date: 2023-12-03 13:07:27.287211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5c2eec8dd2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.String(length=30), nullable=False),
    sa.Column('faculty', sa.String(length=255), nullable=False),
    sa.Column('course', sa.String(length=30), nullable=False),
    sa.Column('group', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student'))
    )
    op.create_index(op.f('ix_student_student_id'), 'student', ['student_id'], unique=True)
    op.create_table('voting_info',
    sa.Column('faculty', sa.String(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voting_info'))
    )
    op.create_table('candidate',
    sa.Column('voting_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('about', sa.String(length=1023), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['voting_id'], ['voting_info.id'], name=op.f('fk_candidate_voting_id_voting_info'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate'))
    )
    op.create_table('user',
    sa.Column('student_id', sa.Integer(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_user_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('tg_user',
    sa.Column('tg_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_tg_user_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tg_id', 'id', name=op.f('pk_tg_user'))
    )
    op.create_table('vk_user',
    sa.Column('vk_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_vk_user_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vk_id', 'id', name=op.f('pk_vk_user'))
    )
    op.create_table('vote_against_all',
    sa.Column('voting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_vote_against_all_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_vote_against_all_user_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voting_id'], ['voting_info.id'], name=op.f('fk_vote_against_all_voting_id_voting_info'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_against_all')),
    sa.UniqueConstraint('student_id', name=op.f('uq_vote_against_all_student_id'))
    )
    op.create_table('vote_for_candidate',
    sa.Column('voting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name=op.f('fk_vote_for_candidate_candidate_id_candidate')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_vote_for_candidate_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_vote_for_candidate_user_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voting_id'], ['voting_info.id'], name=op.f('fk_vote_for_candidate_voting_id_voting_info'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_for_candidate'))
    )
    op.create_table('voter',
    sa.Column('voting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('voter_uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_voter_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_voter_user_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voting_id'], ['voting_info.id'], name=op.f('fk_voter_voting_id_voting_info'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voter')),
    sa.UniqueConstraint('voter_uid', name=op.f('uq_voter_voter_uid')),
    sa.UniqueConstraint('voting_id', 'student_id', name=op.f('uq_voter_voting_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voter')
    op.drop_table('vote_for_candidate')
    op.drop_table('vote_against_all')
    op.drop_table('vk_user')
    op.drop_table('tg_user')
    op.drop_table('user')
    op.drop_table('candidate')
    op.drop_table('voting_info')
    op.drop_index(op.f('ix_student_student_id'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
